#include "str_differencial.h"

int main(){
	int a=0;
	init_lexems();

	string ower("xlnx");
	//	string ower("(lnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnx)^(lnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnlnx)");
	//	string ower("lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnxlnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnxlnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnxlnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnxlnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnxlnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnxlnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnxlnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx^lnx");
	cout << summ_line(ower, a) << '\n';
	system("pause");
}
